language: python
dist: bionic
sudo: false
script: python -m unittest discover
cache: pip
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
after_success: codecov
jobs:
  include:
    - stage: black
      name: 'black'
      python: '3.7'
      install: pip install black
      script: black --check --verbose .
      after_success: skip
    - stage: flake8
      name: 'flake8'
      python: '3.7'
      install: pip install flake8
      script: flake8
      after_success: skip
